### ISSUE TITLE
Recording - Group Channel/ iOS - Register operator, Cancel Registration of operator

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#138]
**[AddRemoveOperatorsGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/AddRemoveOperatorsGroupChannel)**

_Click ‘Create’ to create new group channel
Under ‘Choose Member’, select users & click ‘Ok’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Sunset Crew’
Click ‘Create’
Click on ‘Hockey League’ in Group Channel List
In chat window, click ‘Setting’
Under ‘Choose action for channel’, click ‘Member List’
Click ‘Add Operator’ for a user other than yourself 
Click ‘Close’ on success window
Click ‘Remove Operator’ for that same user to remove them as operator
Click ‘Close’ on success window_

**Comment by petru-gherghel** [comment]
@justinbaldwin - Light
https://drive.google.com/file/d/1N7Aux4wazN2B0YRgrvZk52y3WtZGCoOp/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing

**Comment by justinbaldwin** [comment]
@petru-gherghel trim to mark 0:15.

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1NMu4GiIMbTzYRLxPUqDhBfRlHYsngYAx/view?usp=sharing
