### ISSUE TITLE
Recording - Group Channel/ iOS - Ban and unban users from channel

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#140]
**[BanUnBanUserGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/BanUnBanUserGroupChannel)**

_Click ‘Create’ to create new group channel
Under ‘Choose Member’, select members & click ‘Ok’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Hockey League’
Click ‘Create’
Click on ‘Hockey League’ in Group Channel List_

> Daniel: Let me know if 4pm every Thursday works for a game!
> Drew: Some of us have work Daniel, I don’t want to be part of your team anyway.

 
_In Group Channel Chat window, click ‘Setting’
Under ‘Choose action for channel’, click ‘Member List’
Click ‘Ban’ for Drew
Click ‘Close’ on success window_

**Comment by petru-gherghel** [comment]
Ready

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1UoGgGDw8Vg_djYzgZLYVe_ySxgwvSFQS/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin - Light
https://drive.google.com/file/d/1d_p1SoE7JjTeVBdrWt2agrLyATUK63uu/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

**Comment by michellewong27** [comment]
@justinbaldwin Include a different screen of user that is banned with their screen view not allowing them to interact with group

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1n10U5FhPw5u-j0fxVFJnPJEd6f4yjuC2/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel please record two separate videos. One of Drew being banned from "Hockey League," and a second video logged in as Drew trying to access the channel "Hockey League."

**Comment by petru-gherghel** [comment]
@justinbaldwin 
Recording - Group Channel/ iOS - Ban and unban users from channel[#140] Dew POV.
I tried to sync in the video that Ban operation, but it will need some fine-tuning
https://drive.google.com/file/d/1xVIYDYEglit02LHnagSbphoJFsuEGV6e/view?usp=sharing.

**Comment by justinbaldwin** [comment]
@justinbaldwin get with Olivia to sync up the two videos side by side.

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1K3LlxISofzlmtV_r2Xtb1JMYiFhiRYkm/view?usp=sharing
