### ISSUE TITLE
Recording - Open Channel/ iOS - Create basic channel

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#142]
[BasicOpenChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/BasicOpenChannel)

_Click ‘Create’ to create new open channel
Click on ‘Channel Name’ to input channel name
Name channel ‘Discussion Section’
Click ‘Create’_

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1-SGoqzXjhp0z-tEEajYlJIkWnpXVS9VT/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin - light
https://drive.google.com/file/d/1Rw5KV_WjPhwlj8wwQfk3JyU2hYYS7Emq/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot ready for review.

[https://drive.google.com/file/d/1Rw5KV_WjPhwlj8wwQfk3JyU2hYYS7Emq/view?usp=sharing](https://drive.google.com/file/d/1Rw5KV_WjPhwlj8wwQfk3JyU2hYYS7Emq/view?usp=sharing
)

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing

**Comment by justinbaldwin** [comment]
@petru-gherghel increase speed to 1.5x.

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1uWZUDAlBwXEOOmjiw4fWWOYfF55P6-22/view?usp=sharing
