### ISSUE TITLE
Recording - Group Channel/ iOS - Categorize messages by custom type

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#143]
[CategorizeMessageGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/CategorizeMessageGroupChannel)

Link to documentation:
[https://sendbird.com/docs/chat/v4/ios/guides/open-channel#2-send-a-message
](https://sendbird.com/docs/chat/v4/ios/guides/open-channel#2-send-a-message)

**Comment by justinbaldwin** [comment]
@justinbaldwin possible visualization here that contains an emoji (star, etc) that can categorize messages. I.e. in Slack how you can star a message.

@petru-gherghel

**Comment by petru-gherghel** [comment]
@justinbaldwin 
we are waiting for clarification from Chris, as the "pin messages" is a new feature.

**Comment by justinbaldwin** [comment]
@petru-gherghel Thank you! Once the feature is complete we can revisit the recordings.

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1s--phwdDye196NMyQpnbsC64qQo7Z3WR/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot @michellewong27

Ready for review.
