### ISSUE TITLE
Recording - Group Channel/ iOS - Channel types

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#147]
**[ChannelTypesGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/ChannelTypesGroupChannel)**

_Open the Sendbird Dashboard
On left hand side bar, click Group Channels
On top right corner, click ‘Create channel’
Click on ‘name’ textfield, name the channel here & type: ‘Movie Night’
Click on ‘custom type’ textfield, name the channel here & type: ‘horror’
Click ‘next’ button
Enter ‘nickname’ in textfield to invite users
Type user ‘Drew’ & click ‘Done’
~Conversation will open, move pointer around right hand sidebar to show that ‘custom type’ has ‘horror’_

**Comment by petru-gherghel** [comment]
Ready

**Comment by petru-gherghel** [comment]
@justinbaldwin 
Scripted version:
https://drive.google.com/file/d/11eVEPLFuLACSi8rd77jNVDmEhHsS227r/view?usp=sharing
My proposal, the task is: Report a message, a user, or a channel, and the scripted version is covering only the report message, in V1, I covered report user, and channel as well:
https://drive.google.com/file/d/1LlfPJ_Es0FYZqElkH19uFEcV3iFxEJV3/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
i'm following the script, and when I'm trying to add an user to the new channel, I get an message saying that a connection must be made first.

![Image](https://user-images.githubusercontent.com/102351060/177768402-141e76db-21bf-4374-badb-009ca425e4a3.png)

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1JXz9-AY2oJkrjFoPoeKa-Sl0A6G0FKrG/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel please crop this video in this way shown.


![Image](https://user-images.githubusercontent.com/102265523/178017273-e11134e4-ecd1-46e3-a6bb-3929c17e1eef.png)

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1ufU5_KSLpjmR2n8XHTAK7vvqOJoa04P2/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
