### ISSUE TITLE
Recording - Open Channel/ iOS - Copy message

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#148]
**[CopyMessageOpenChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/CopyMessageOpenChannel)**

_Create two open channels: ‘Cat Clan ‘ and ‘Life as a dog’
Enter 1st open channel ‘Cat Clan’_

> Joyce: I’m available to babysit for the 4th of July weekend!

_As user ‘Joyce’, hold down the message above that was sent & select ‘Copy’
Select the open channel you want to paste the message into 
Open the open channel you pasted the message into & see that the message was sent into this channel as well_

**Comment by petru-gherghel** [comment]
Ready

**Comment by petru-gherghel** [comment]
@justinbaldwin 

https://drive.google.com/file/d/1-SGoqzXjhp0z-tEEajYlJIkWnpXVS9VT/view?usp=sharing
https://drive.google.com/file/d/1KNA7YdmmyuG1NnNL7WczWpAvZ_jUgGC8/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin - light
https://drive.google.com/file/d/17TseLgbP1bN5YV_teJfwUUG939BNB9so/view?usp=sharing
https://drive.google.com/file/d/1JciKSWws8Pjre_okm3hnBbTPU4vcY-yB/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

[https://drive.google.com/file/d/1JciKSWws8Pjre_okm3hnBbTPU4vcY-yB/view](https://drive.google.com/file/d/1JciKSWws8Pjre_okm3hnBbTPU4vcY-yB/view)

**Comment by michellewong27** [comment]
Channel name should be ‘Life as a dog’ not ’Life is a dog’

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1CwDzYhGHxfLeJGeGTcGe0VERRFwwRQkj/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1CwDzYhGHxfLeJGeGTcGe0VERRFwwRQkj/view?usp=sharing
