### ISSUE TITLE
Recording - Open Channel/ iOS - Delete message

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#149]
**[DeleteMessageOpenChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/DeleteMessageOpenChannel)**

_Click ‘Create’ to create new open channel
Name channel ‘Foodies’
Click ‘Create’
Enter ‘Foodies’ channel_

> Omar sends: I completely forgot about our dinner plans tonight, was the reservation for 5:00pm?
> Daniel sends: No, it’s at 6:00 pm now. Joyce changed it last night
> Joyce sends at the same time as Daniel: I changed it to 6:00 instead!

_As user ‘Joyce’, hold down message sent above
Click ‘Delete’_

**Comment by petru-gherghel** [comment]
Ready

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1iOI2CD7zeqP6zm9sR_ihSMgW0oHEuJGa/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin - Light
https://drive.google.com/file/d/1cIjhaQx83JqsArqar_FshedJ6nvFeYJi/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

[https://drive.google.com/file/d/1cIjhaQx83JqsArqar_FshedJ6nvFeYJi/view?usp=sharing](https://drive.google.com/file/d/1cIjhaQx83JqsArqar_FshedJ6nvFeYJi/view?usp=sharing)
