### ISSUE TITLE
Recording - Group Channel/ iOS - Freeze and unfreeze channel

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#150]
**[FreezeUnFreezeGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/FreezeUnFreezeGroupChannel)**

_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘ Europe Trip’
Click ‘Create’
Enter ‘Europe Trip’ group channel
Click ‘Setting’
Under ‘Choose action for channel’, click ‘Freeze Channel’
When success window pops up, click ‘Close’
In ‘Europe Trip’ group channel, click ‘Setting’
Under ‘Choose action for channel’, click ‘Unfreeze Channel’
When success window pops up, click ‘Close’
In ‘Europe Trip’ group channel, click ‘Setting’ to show that it is now unfrozen_

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

[https://drive.google.com/file/d/1m60_5E3jz1OKD4e-iyY0JFD38FWiWKqR/view?usp=sharing](https://drive.google.com/file/d/1m60_5E3jz1OKD4e-iyY0JFD38FWiWKqR/view?usp=sharing)

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing

**Comment by justinbaldwin** [comment]
@petru-gherghel trim to the 0:28 mark, and increase speed to 1.5x

**Comment by michellewong27** [comment]
@michellewong27 reviewed, good for publishing
