### ISSUE TITLE
Recording - Open Channel/ iOS - Generate thumbnails of file message

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#151]
**[GenerateThumbnailForFileOpenChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/GenerateThumbnailForFileOpenChannel)**

Link to documentation:
[https://sendbird.com/docs/chat/v4/ios/guides/group-channel#2-send-a-message](https://sendbird.com/docs/chat/v4/ios/guides/group-channel#2-send-a-message)

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1l72WoOfQb3sy4Jh3fgVv1YxGZSWlwbD_/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1l72WoOfQb3sy4Jh3fgVv1YxGZSWlwbD_/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
