### ISSUE TITLE
Recording - Group Channel/ iOS - Hide or archive channel from a list of channels

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#152]
**[HideOrArchiveGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/HideOrArchiveGroupChannel)**

Link to documentation:
[https://sendbird.com/docs/chat/v3/ios/guides/group-channel#2-hide-or-archive-a-channel-from-a-list-of-channels](https://sendbird.com/docs/chat/v3/ios/guides/group-channel#2-hide-or-archive-a-channel-from-a-list-of-channels )

**Comment by petru-gherghel** [comment]
@justinbaldwin 
for this one, I made two videos, one shorter, and a longer one, but at 1.25x speed.
Short version: https://drive.google.com/file/d/1Cy-2z8bWgRNHDkB12-zZmTWOZEYDuZgL/view?usp=sharing
Longer version: https://drive.google.com/file/d/1gZZjUk_7tLPBTlTpLDzdZ3rBvK6gsBYz/view?usp=sharing
