### ISSUE TITLE
Recording - Group Channel/ iOS - Caching with Local Caching

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#153]
**[LocalCachingGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/LocalCachingGroupChannel)**

Link to documentation:
[https://sendbird.com/docs/chat/v4/ios/guides/group-channel-collection#1-group-channel-collection](https://sendbird.com/docs/chat/v4/ios/guides/group-channel-collection#1-group-channel-collection)

**Comment by petru-gherghel** [comment]
@justinbaldwin 
this is for Yogesh

**Comment by YogeshVeer** [comment]
This feature cannot be demoed since it is technical which local cache is available from SDK itself. Other than showing the code.
