### ISSUE TITLE
Recording - Group Channel/ iOS - Retrieve members who have read a message

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#155]
**[MembersReadMessageGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/MembersReadMessageGroupChannel)**

_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Baseball Game’
Click ‘Create’
Click ‘Baseball Game’ to enter conversation_

> Joyce: Let's coordinate tomorrow’s baseball game here

_Click on message above, show Message info & Read By: No members read the message_

**Comment by petru-gherghel** [comment]
Ready

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1t3_e8Wv2J5Kv5WmssffkLBSbBk7zg57N/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin - Light
https://drive.google.com/file/d/1gSSJIrXaECiMqU_GpOVHfZoDB9CC4ZsQ/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

[https://drive.google.com/file/d/1gSSJIrXaECiMqU_GpOVHfZoDB9CC4ZsQ/view?usp=sharing](https://drive.google.com/file/d/1gSSJIrXaECiMqU_GpOVHfZoDB9CC4ZsQ/view?usp=sharing)

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1fMLyCqs1ZrhOgrqcpnxEjUTd7g_5qPYF/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
