### ISSUE TITLE
Recording - Group Channel/ iOS - Retrieve number of members who haven't read a message

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#156]
**[MembersUnReadMessageGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/MembersUnReadMessageGroupChannel)**

_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Holiday Party’
Click ‘Create’
Click ‘Holiday Party’ to enter conversation_

> Joyce: We should start planning our holiday party. Feel free to throw out any ideas!

_Click on message above, show Message info & Unread By: users in the group channel_

**Comment by petru-gherghel** [comment]
Ready

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1qMkXsR165hN29aMnsGTZW8NmjLGcJhVc/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

**Comment by justinbaldwin** [comment]
@petru-gherghel please change the text to "Let's start planning our holiday party here!"

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1lt2a3GaYcuwah_sYUSpgBAi0kKtCbYD1/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1lt2a3GaYcuwah_sYUSpgBAi0kKtCbYD1/view?usp=sharing
