### ISSUE TITLE
Recording - Group Channel/ iOS - Mention other members in message

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#157]
**[MentionUsersInMessageGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/MentionUsersInMessageGroupChannel)**

_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Puppy playdate’
Click ‘Create’
Click ‘Puppy playdate’ to enter conversation_

> Joyce: Are we still meeting at the park later? 

_Click the text box and type ‘Daniel, if you’re coming please bring the ball!’ 
Click the send button
Under ‘Choose Member’, click the user you want to mention: ‘Daniel’ & click ‘OK’_

**Comment by petru-gherghel** [comment]
Ready

**Comment by justinbaldwin** [comment]
@justinbaldwin review with Olivia.

@petru-gherghel Olivia and I are going to meet about speeding up only certain segments of the video. Will report back.

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/16RkC74XEIDnC-iK_WkmgQ70uAP1QfTR-/view?usp=sharing

**Comment by justinbaldwin** [comment]
@justinbaldwin please speed up the text entry

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ar7Mea0lqQ-8dbbw9Sy3ZJkide30gVCf/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
