### ISSUE TITLE
Recording - Open Channel/ iOS - Mention other participants in message

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#158]
**[MentionUsersInMessageOpenChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/MentionUsersInMessageOpenChannel)**

_Click ‘Create’ to create new open channel
Click on ‘Channel Name’ box to input channel name
Name channel ‘Game Night’
Click ‘Create’
Click ‘Game Night’ to enter conversation_

> Joyce: Is there any way we could start around 8? I have to run to the pharmacy first!

_Click the text box and type ‘Amelia, could you please grab food on the way?’ 
Click the send button
Under ‘Choose Member’, click the user you want to mention: ‘Amelia’ & click ‘OK’
(Have to make sure that the user you want to mention is online in order to tag/ be able to mention them)_

**Comment by petru-gherghel** [comment]
Ready

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1cXzieIuPw092_Rofply-VfDZ48Lisicc/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel adjust speed to 1.75x.

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1zJUqLXINQkuF0bgfFqo0yJ10Wcr2sV5F/view?usp=sharing
