### ISSUE TITLE
Recording - Group Channel/ iOS - Message threading

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#159]
**[MessageThreadingGroupChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/MessageThreadingGroupChannel)**

_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Hobby Time’
Click ‘Create’
Click ‘Hobby Time’ to enter conversation_

> Joyce: Found a book club that meets every Thursday. Who’s in?!

_Hold down Joyce’s message 
Click ‘Reply’
In the ‘Reply to message’ window, type ‘I’m in!’ 
Click the ‘Confirm’ button_

**Comment by petru-gherghel** [comment]
Ready for Petru

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

**Comment by justinbaldwin** [comment]
@petru-gherghel adjust speed to 1.5x.
