### ISSUE TITLE
Recording - Open Channel/ iOS - Message threading

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#160]
**[MessageThreadingOpenChannel](https://github.com/sendbird/sendbird-chat-sample-ios/tree/main/Apps/MessageThreadingOpenChannel)**

_Click ‘Create’ to create new open channel
Click on ‘Channel Name’ box to input channel name
Name channel ‘Pets Place’
Click ‘Create’
Click ‘Pets Place’’ to enter conversation_

> Joyce: Does anyone have a good trainer to recommend for my 8 week old puppy?

_Hold down Joyce’s message 
Click ‘Reply’
In the ‘Reply to message’ window, type ‘My friend Omar is an excellent puppy trainer! He’s been in the business for around 20 years.’ 
Click the ‘Confirm’ button_

**Comment by petru-gherghel** [comment]
Ready for Petru

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1S0oe9PWpp32k82RQLPHQMnnvjWNKB05B/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

[https://drive.google.com/file/d/1S0oe9PWpp32k82RQLPHQMnnvjWNKB05B/view?usp=sharing](https://drive.google.com/file/d/1S0oe9PWpp32k82RQLPHQMnnvjWNKB05B/view?usp=sharing
)

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1EkaSy_YA57yL3iRs98BW_tj9-15kGoQl/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1EkaSy_YA57yL3iRs98BW_tj9-15kGoQl/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
