### ISSUE TITLE
Recording - Group Channel/ iOS - Mute and unmute users in channel

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#161]
_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Movie Junkies’
Click ‘Create’
Click ‘Movie Junkies’ to enter conversation_

> Joyce: Call me crazy, but I’ve never seen Star Wars
> Daniel: ‘No way!’
> Omar: That’s my favorite! I need to tell you what happens!
> Joyce: No spoilers please!

_Click ‘Setting’
Click ‘Member List’
Select user to mute by clicking ‘Mute’ next to Chris’s name
When success window appears, click ‘Close’_

> Joyce: I had to mute Omar for now, he’ll be unmuted once I finish the movie!

_Now user is muted, click ‘Unmute’ to unmute user
When success window appears, click ‘Close’_

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1dGzZPzAtocYbbBF22BlYc92NAJhIXRPV/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel 

"tell" is misspelled, shown below.


![Image](https://user-images.githubusercontent.com/102265523/176688664-98bc6d61-541b-4176-a14b-90a6dd66f793.png)

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/18Ljgp4VA7G1ZJy-Ewp-v9Xn6kz4SCcc4/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

https://drive.google.com/file/d/18Ljgp4VA7G1ZJy-Ewp-v9Xn6kz4SCcc4/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing

**Comment by justinbaldwin** [comment]
@justinbaldwin review with Olivia.

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1OEhHLA0HLCrNytsLl6JmacqInADMcqdh/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel 

Please cut between 0:02-0:04

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1RU85sOEd4621qtNX2S43SNkWzN2f7gAy/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin can we make this video 1.5x speed?

**Comment by justinbaldwin** [comment]
@michellewong27 Can do!

@petru-gherghel increase overall speed by 1.5x please. Thank you!

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1lww2qtbjPUHY7CGX-QkeJTiJDxpFM-Md/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1lww2qtbjPUHY7CGX-QkeJTiJDxpFM-Md/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
