### ISSUE TITLE
Recording - Group Channel/ iOS - Retrieve a list of banned or muted users

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#162]
_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Roommates’
Click ‘Create’
Click ‘Roommates’ to enter conversation
Click ‘Setting’, click ‘Muted Users’ to show list of muted users
Click ‘Setting’, click ‘Banned Users’ to show list of muted users_

> Nadia: Can everyone send me the money for utilities this month?
> Amelia: I moved out halfway through the month so I don’t think I should pay
> Emily: Nobody liked you anyway

_On the Dashboard, on left hand sidebar click ‘Group channels’ & click on ‘Roommates’
In the chat window, on the right hand sidebar click ‘Members’ and click on Amelia
Click ‘Ban’ & input ‘Reason for muting’ as ‘No longer a roommate’
Click on Emily, click ‘Mute’ & input ‘Reason for muting’ as ‘Inappropriate behavior’
Click  ‘<-’ back arrow to go back to settings sidebar
Click on ‘Banned’ to view banned now shows Amelia
Click  ‘<-’ back arrow to go back to settings sidebar
Click on ‘Muted’ to view banned now shows Emily_

**Comment by petru-gherghel** [comment]
@justinbaldwin 
same issue as #147

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1NCfqTXtXpAbqIBY95vCNfQ7vr2Smt6et/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel start video at around the 0:10 second mark.

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1KoZJbnjoYjLHgS3h75TlkSoWq41rGVu-/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1KoZJbnjoYjLHgS3h75TlkSoWq41rGVu-/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
