### ISSUE TITLE
Recording - Group Channel/ iOS - Display Open Graph tags in a message

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#163]
Link to documentation:
[https://sendbird.com/docs/chat/v3/ios/guides/group-channel-advanced#2-display-open-graph-tags-in-a-message](https://sendbird.com/docs/chat/v3/ios/guides/group-channel-advanced#2-display-open-graph-tags-in-a-message)

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1eGzo5OSKEYc7NVOKa6Yki6Ltl04YEe7O/view?usp=sharing
