### ISSUE TITLE
Recording - Group Channel/ iOS - Retrieve a list of members and operators in a specific order

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#166]
Link to documentation:
[https://sendbird.com/docs/chat/v3/ios/guides/group-channel#2-retrieve-a-list-of-members-and-operators-in-a-specific-order](https://sendbird.com/docs/chat/v3/ios/guides/group-channel#2-retrieve-a-list-of-members-and-operators-in-a-specific-order)

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1DBc0tezqv0O2nGQmunOre4Ap0cwAph3B/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1DBc0tezqv0O2nGQmunOre4Ap0cwAph3B/view?usp=sharing
