### ISSUE TITLE
Recording - Group Channel/ iOS - Push notifications

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#167]
_Upon opening/running the application, a window will pop up before sign in that says ‘ “PushNotificationsTranslationGroupChannel” Would Like to Send You Notifications ‘, click ‘Allow’
Login with user ID 
From home screen, on bottom right click ‘Setting’
Press toggle for Push Notifications (this will enable it)_

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ctpPAzPHDvt-Pie5Lb2-Iq_D1j1MA7jl/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
