### ISSUE TITLE
Recording - Group Channel/ iOS - Push notification translation

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#168]
Link to documentation:
[https://sendbird.com/docs/chat/v3/ios/guides/push-notifications#2-push-notification-translation](https://sendbird.com/docs/chat/v3/ios/guides/push-notifications#2-push-notification-translation)

**Comment by petru-gherghel** [comment]
@justinbaldwin 
this is for Yogesh

**Comment by YogeshVeer** [comment]
Push notification cannot be tested/demo since we do not have profiles to verify.
