### ISSUE TITLE
Recording - Group Channel/ iOS - React to a message

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#169]
_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Study Crew’
Click ‘Create’
Click on ‘Study Crew’ to enter conversation_

> Drew: Big announcement: just got my grades back and aced the final!
> Emily: Congratulations Drew!
> Nadia: So proud of you!

_Amelia reacts to Drew’s message with clapping emoji_

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
