### ISSUE TITLE
Recording - Group Channel/ iOS - Report a message, a user, or a channel

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#170]
_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Gamers Unite’
Click ‘Create’
Click on ‘Gamers Unite’ to enter conversation_

> Joyce: Are we back on to play tonight? Same team?
> Daniel: We gotta beat those guys this time. They’re solid.
> Drew: Probably a bunch of losers from third world countries

_Hold down Drew’s message, pop up will appear to ‘Choose action for message’
Click ‘Report this message’
Success window will appear, click ‘Close’_

**Comment by petru-gherghel** [comment]
@justinbaldwin 
scripted version: https://drive.google.com/file/d/1OWjP7-i3o2UJkG4ipY3SrDhJe1pIRKoE/view?usp=sharing
My proposal, the task is: Report a message, a user, or a channel, and the scripted version is covering only the report message, in V1, I covered report user, and channel as well:
https://drive.google.com/file/d/1LFDoFLPqYf9PKlCn0F9WkyS5stHPdgE0/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel  change script to this please.

> Joyce: Are we back on to play tonight? Same team?
> Daniel: We gotta beat those guys this time. They’re solid.
> Drew: Probably a bunch of losers!

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1uQnVJ5bnGFNtKmFtDurpjC-hqM7E27U9/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1uQnVJ5bnGFNtKmFtDurpjC-hqM7E27U9/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
