### ISSUE TITLE
Recording - Open Channel/ iOS - Report a message, a user, or a channel

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#171]
_Click ‘Create’ to create a new open channel
Name channel ‘Investor Advice’
Click ‘Create’
Click on ‘Investor Advice’ to enter conversation_

> Joyce: Crypto is on fire! My low cap stocks are up 500%
> Daniel: Same here, time to retire soon?
> Oliver: Insider info: Acme co is about to announce an acquisition. Short it now

_Hold down Oliver’s’ message, pop up will appear to ‘Choose action for message’
Click ‘Report this message’
Success window will appear, click ‘Close’_

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

[https://drive.google.com/file/d/1LlfPJ_Es0FYZqElkH19uFEcV3iFxEJV3/view](https://drive.google.com/file/d/1LlfPJ_Es0FYZqElkH19uFEcV3iFxEJV3/view)

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
