### ISSUE TITLE
Recording - Open Channel/ iOS - Send and receive various types of files

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#172]
_Click ‘Create’ to create a new open channel
Name channel ‘Master Chefs’
Click ‘Create’
Click on ‘Master Chefs’ to enter conversation_

> Joyce: Daniel, you have to update us on the cooking class! How was it?
> Daniel: My dish turned out amazing. Check it out!

_Click ‘+’ button in bottom left corner
Select ‘Choose Album’, select ‘Choose from Library’ and select photo to add_

> Daniel: I’ll send you guys the instructions the chef sent out to us as well!

_Click ‘+’ button in bottom left corner
Select ‘Upload PDF’_

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1ml5jQ5iVtZB1adOU696N3VTDZnbIJspG/view?usp=sharing
photo downloaded from here: https://www.foodiesfeed.com/free-food-photo/bowl-full-of-fresh-strawberries-2/download/

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

https://drive.google.com/file/d/1ml5jQ5iVtZB1adOU696N3VTDZnbIJspG/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing

**Comment by justinbaldwin** [comment]
@justinbaldwin review with Olivia.

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1VMxuYsmzYCxspnM6Vm78FQHogrYkwAex/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
I had no guidelines, but I increased the speed of the video as follows:
-overall video is now at 1.5x speed
- Text input is now at 1.85x speed
https://drive.google.com/file/d/1cPZOUFjPdtdPARO-rj1XgnbddzoSDC2I/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
