### ISSUE TITLE
Recording - Group Channel/ iOS - Track and cancel file upload progress

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#173]
Links to documentation:

[https://sendbird.com/docs/chat/v3/ios/guides/group-channel-advanced#2-track-file-upload-progress-using-a-handler](https://sendbird.com/docs/chat/v3/ios/guides/group-channel-advanced#2-track-file-upload-progress-using-a-handler) 
[https://sendbird.com/docs/chat/v3/ios/guides/group-channel-advanced#2-cancel-an-in-progress-file-upload ](https://sendbird.com/docs/chat/v3/ios/guides/group-channel-advanced#2-cancel-an-in-progress-file-upload )

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1Bs22Tj5i8Z-xxu11v9bRD0kRi97n70fE/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1Bs22Tj5i8Z-xxu11v9bRD0kRi97n70fE/view?usp=sharing
