### ISSUE TITLE
Recording - Group Channel/ iOS - Typing indicator

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#174]
_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Family Plans’
Click ‘Create’
Click on ‘Family Plans’ to enter conversation_

> Oliver: Should we do lunch at 11:00 am? 
> Drew: 11:00 am works for me!

_Behind the scene: With another window open, login as Amelia & enter the group channel. Have Amelia type the message:_ 

> I have a meeting until 11:30, could we have lunch at 12?

_From Oliver’s screen, see/capture that Amelia is typing
Have Amelia send the message_

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1K4rlKd8WpHlYMMkyQLtX9VUfZLbCwKEX/view?usp=sharing

**Comment by justinbaldwin** [comment]
@chrischabot ready for review

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing

**Comment by justinbaldwin** [comment]
@petru-gherghel increase speed to 1.5x.

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1bS-AzO32hev7aPb1bJkbWHAHlxT3AAte/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1bS-AzO32hev7aPb1bJkbWHAHlxT3AAte/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
