### ISSUE TITLE
Recording - Group Channel/ iOS - Update or delete message by operators

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#175]
_Click ‘Create’ to create new group channel
Under ‘Choose member’, add users & select ‘OK’
Click on ‘Channel Name’ box to input channel name
Name channel ‘Birthday Ideas’
Click ‘Create’
Click on ‘Birthday Ideas’ to enter conversation_

> Drew: Hey guys, do you think we should get roses or pink lilies for Emily’s birthday?
> Daniel: Hm they’re both great options
> Nadia: Not sure
> Nadia: Oh, I remember she loves lilies so I would go with that!

_Hold down my message above as Nadia, pop up will appear to ‘Choose action for message’
Click ‘Update’, and update the message to ‘She loves pink lilies so I would go with that!’
Click ‘Confirm’
Hold down my message as Nadia saying ‘Not sure’ and click ‘Delete’_

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1HLHetjZTONE15TFIBGXRnWkIUH12wsPm/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel to re-upload new version.

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1yXbPVMATAQe8GT2Eov-A6LBtfIZ1DEqC/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1yXbPVMATAQe8GT2Eov-A6LBtfIZ1DEqC/view?usp=sharing

The final taps on "Joyce" are to show that the current user is not an operator in that specific channel, and thusly cannot make changes to Joyce's post.

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
