### ISSUE TITLE
Recording - User/ iOS - Nick name & profile image

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#178]
_Create a user ‘Emily’
Login with user ID 
From home screen, on bottom right click ‘Setting’
Click ‘Edit User Profile’
Click image icon, select ‘Choose from Library’ & select a photo
Click on the name of user ‘Emily’, change it to Em
Select ‘Done’
Open existing open channel conversation, see that the user’s name & photo is now updated_

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1pQt30yh5_LuGzi2k_v2CmRpYRl9L8e8C/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel trim video to 0:22

**Comment by michellewong27** [comment]
@justinbaldwin video cut off before finishing script steps: _Select ‘Done’.
Open existing open channel conversation, see that the user’s name & photo is now updated_

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1Yay8-MOaI9GqCY1mGeUS7YqOZVRcDQDA/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1aF6tik0BygJ3EtrKEpv4ajiiB23kZARP/view?usp=sharing

**Comment by petru-gherghel** [comment]
@justinbaldwin 
I made two videos:
I decreased the speed with 15%, until 14, but the text input and profile image loading time is has the same pace
https://drive.google.com/file/d/19QxshuiDkI2wtawLx47w_YKz6VnbyMo-/view?usp=sharing
this one, is as required
https://drive.google.com/file/d/1R3Ad8mrd1dPLfXEuv8CoVZqipYff6NSc/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel I prefer the first example you made, thanks a ton Petru!
