### ISSUE TITLE
Recording - Group Channel/ iOS - Retrieve the online status of members

### ISSUE THREAD

**Issue by justinbaldwin** [sendbird/sendbird-chat-sample-ios#179]
Link to documentation:
[https://sendbird.com/docs/chat/v3/unity/guides/group-channel#2-retrieve-the-online-status-of-members ](https://sendbird.com/docs/chat/v3/unity/guides/group-channel#2-retrieve-the-online-status-of-members )

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1Vq8X-G0iNqgRCtdrL3M5O9Vpah2El9GI/view?usp=sharing

**Comment by justinbaldwin** [comment]
@petru-gherghel replace comma with a period in the sentence.

**Comment by petru-gherghel** [comment]
@justinbaldwin 
https://drive.google.com/file/d/1IWzUC48jhx3hic3yKu9yNdA7I2BsD8L1/view?usp=sharing

**Comment by justinbaldwin** [comment]
@michellewong27 @chrischabot 

Ready for review: https://drive.google.com/file/d/1IWzUC48jhx3hic3yKu9yNdA7I2BsD8L1/view?usp=sharing

**Comment by michellewong27** [comment]
@justinbaldwin reviewed, good for publishing
